### ISSUE TITLE
Automatic conversion of Lua table to Go slice?

### ISSUE THREAD

**Issue by dnaeon** [layeh/gopher-luar#12]
If I have a Go struct with one field in it - a slice of strings - is there a way to automatically convert a Lua table to Go slice, if I want to change the contents of my struct from Lua?

I've noticed that stevedonovan/luar does this, so wondering if layeh/gopher-luar supports this as well?

Thanks,
Marin

**Comment by bontibon** [comment]
For clarification, you're looking to do something like the following:

```go
struct X struct {
   S []string
}

L.SetGlobal("x", luar.New(L, &X{}))
```

```lua
x.S = {"a", "b", "c"}
```

Is that correct?

**Comment by bontibon** [comment]
I can see where this can be useful. I'll be pushing a fix for it soon.

**Comment by dnaeon** [comment]
Hey Tim,

Yes, that's exactly what I was looking for.

Sorry, for not providing the code sample myself, but was on phone when
writing this one.

Thanks for looking into this one!

**Comment by dnaeon** [comment]
That was fast! Thanks a lot!
