### ISSUE TITLE
Adding custom metamethods to types?

### ISSUE THREAD

**Issue by dnaeon** [layeh/gopher-luar#13]
I'm trying to find a way to add some metamethods such as `__len` to my Go types, so I can extend their functionality.

Considering the following code below I'd like to retain access to my Go type's methods, but also add a `__len` metamethod to it, so I can get the length of items/persons using the hash `#` operator.

Here's the example code I have.

```go
package main

import (
	"log"

	"github.com/layeh/gopher-luar"
	"github.com/yuin/gopher-lua"
)

type Person struct {
	Name string `luar:"name"`
	Age  int    `luar:"age"`
}

type People struct {
	everyone []*Person `luar:"-"` // Hidden field
}

func (p *People) Add(who ...*Person) {
	p.everyone = append(p.everyone, who...)
}

func (p *People) Len() int {
	return len(p.everyone)
}

func main() {
	L := lua.NewState()
	defer L.Close()

	people := &People{
		everyone: make([]*Person, 0),
	}

	L.SetGlobal("Person", luar.NewType(L, Person{}))
	L.SetGlobal("People", luar.New(L, people))

	code := `
	kevin = Person()
	kevin.name = "Kevin"
	kevin.age = 30

	bob = Person()
	bob.name = "Bob"
	bob.age = 31

	People:add(kevin, bob)
	print("The number of persons I know is " .. People:len())

	-- How to add __len metamethod to People so we can use #People as well?
	`

	if err := L.DoString(code); err != nil {
		log.Fatal(err)
	}
}
```

Considering this code, is there a way to get the length of persons using `#People` instead of calling my custom `People.Len()` method?

Thanks,
Marin

**Comment by bontibon** [comment]
Give the following a try:

```go
people := &People{
    everyone: make([]*Person, 0),
}

mt := luar.MT(L, people)
mt.RawSetString("__len", luar.New(L, (*People).Len))

L.SetGlobal("Person", luar.NewType(L, Person{}))
L.SetGlobal("People", luar.New(L, people))
```

**Comment by dnaeon** [comment]
Sweet, works like a charm! I was trying to use something similar, but instead of using `RawSetString` was trying with `SetField` on the metatable, which didn't work out.

Thanks again for your quick help!
