### ISSUE TITLE
calling go method from lua that returns a slice

### ISSUE THREAD

**Issue by miquels** [layeh/gopher-luar#15]
I'm calling a Go method on an object that returns a slice.. but it seems that slice is not converted to a lua table. What am I doing wrong?

```
package main

import (
        "github.com/yuin/gopher-lua"
        "github.com/layeh/gopher-luar"
)

type Foo struct {}

func (f *Foo) GetValues() (v []string) {
        return []string{ "one", "two", "three" }
}

const code = `
          f = somevar:GetValues()
          for i, v in ipairs(f) do
            print (v)
          end
        `

func main() {
        L := lua.NewState()
        defer L.Close()

        somevar := &Foo{}
        L.SetGlobal("somevar", luar.New(L, somevar))

        if err := L.DoString(code); err != nil {
                panic(err)
        }
}
```

This results in
panic: <string>:3: bad argument #1 to ipairs (table expected, got userdata)

If I replace ipairs(f) with f(), I get:
panic: <string>:3: attempt to call a non-function object

Thanks

Mike.

**Comment by bontibon** [comment]
Unfortunately, Lua 5.1 doesn't support the `__ipairs` metatable field. This means that `ipairs` cannot be used for iterating over luar slices. Here's an alternative that will work for you:

```lua
          f = somevar:GetValues()
          for i = 1, #f do
            v = f[i]
            print (v)
          end
```

**Comment by bontibon** [comment]
Thinking more on it now, slices should probably define `__call` to return an iterator, similar to how maps work. I may add this functionality soon.

**Comment by miquels** [comment]
Wow, that was fast!

Thanks a lot,

Mike.

**Comment by bontibon** [comment]
If you update luar (`go get -u github.com/layeh/gopher-luar`), the following should now work:

```lua
          f = somevar:GetValues()
          for i, v in f() do
            print (v)
          end
```

**Comment by miquels** [comment]
It works. Thanks again!
