### ISSUE TITLE
How can I use luar to make a const table to lua?

### ISSUE THREAD

**Issue by ckcfcc** [layeh/gopher-luar#18]
How can I use luar to make a const table to lua?

Can I use some struct config like `luar:"cosnt"` to do this?

**Comment by bontibon** [comment]
Can you be a little more detailed? Explain how luar currently works and what you would like to happen.

**Comment by ckcfcc** [comment]
I want to regist some object like this

// regist MyGoObj and GetGoObj() to lua
type MyGoObj struct {
  Var1 int
}

func GetGoObj() *MyGoObj {
  return &MyGoObj {}
}

-------------------------(in lua)

myGoObj = GetGoObj() -- GetGoObj() is a api, the can get a go object
print(myGoObj.Var1) -- output 1
myGoObj.Var1 = 2 -- error, Var1 can't be change. <-- I want to know,how can I regist the myGoObj

**Comment by bontibon** [comment]
As mentioned in #19, I feel this is out of scope of the library.

**Comment by TomNZ** [comment]
You can find both transparent pointer behavior, and immutability options for reflected values on this fork: https://github.com/oscarhealth/gopher-luar
