### ISSUE TITLE
Failed to import - expects import "layeh.com/gopher-luar"

### ISSUE THREAD

**Issue by gpolek** [layeh/gopher-luar#22]
Hi,

I am trying to build the gopher-luar with newest version of go on mac, and it fails with error expecting import of `layeh.com/gopher-luar`. Please see below:

```
$ make                                                                                                                                                                           gopher-luar/git/master
go test -coverprofile=coverage.out
can't load package: package github.com/layeh/gopher-luar: code in directory /Users/gpolek/workspace/src/github.com/layeh/gopher-luar expects import "layeh.com/gopher-luar"
```

Why the comments introduced in https://github.com/layeh/gopher-luar/commit/24588ee686c85f1048484a20f024e9d344740511 were added in first place? It breaks the build for me. After removing `// import "layeh.com/gopher-luar"` everything compiles correctly. 

Here is my version of go:

```
go version
go version go1.7.4 darwin/amd64
```

Best,
Greg

**Comment by bontibon** [comment]
The import path for the package had to move from `github.com/layeh/gopher-luar` to `layeh.com/gopher-luar`. Simply change all of your import statements accordingly.
