### ISSUE TITLE
Test_metatable broken on master?

### ISSUE THREAD

**Issue by TomNZ** [layeh/gopher-luar#25]
I'm seeing the above test failing in master, not sure if it's just something in my setup...

```--- FAIL: Test_metatable (0.00s)
	helpers_test.go:80: error substring 'attempt to call' not found in 'runtime error: invalid memory address or nil pointer dereference
		stack traceback:
			<string>:1: in main chunk
			[G]: ?'
FAIL
FAIL	layeh.com/gopher-luar	4.028s```

**Comment by bontibon** [comment]
No errors for me with layeh/gopher-luar@ab3f305945becf90dbde5962755dc044cb78acee and yuin/gopher-lua@eed1c7917d2f4a7bbed5e9bf6a0ce64cbd2918c5.

**Comment by TomNZ** [comment]
Ahh, updating `gopher-lua` did it, apologies!
