### ISSUE TITLE
how to modify Config

### ISSUE THREAD

**Issue by edolphin-ydf** [layeh/gopher-luar#28]
since there is `FieldNames` and `MethodNames` in `Config`, and the default export the upper case and lower case field and method name. but in my usage, only upper case is needed. so is there a way to set the two field in `Config` and how? thanks for your help.

**Comment by bontibon** [comment]
Try the following:

```go
cfg := luar.GetConfig(state)
cfg.FieldNames = func(s reflect.Type, f reflect.StructField) []string {
    return []string{f.Name}
}
cfg.MethodNames = func(t reflect.Type, m reflect.Method) []string {
    return []string{m.Name}
}
```

**Comment by edolphin-ydf** [comment]
> Try running the following before converting any data with `luar.New`:
> 
> ```go
> cfg := luar.GetConfig(state)
> cfg.FieldNames = func(s reflect.Type, f reflect.StructField) []string {
>     return []string{f.Name}
> }
> cfg.MethodNames = func(t reflect.Type, m reflect.Method) []string {
>     return []string{m.Name}
> }
> ```

ok, it works. thanks
