### ISSUE TITLE
panic:  attempt to call a non-function object when iterating a map.

### ISSUE THREAD

**Issue by bbuck** [layeh/gopher-luar#3]
I'm trying to iterate over a Go maps keys and values but I keep running into this problem.

The simple version of the Lua

```lua
function doWork(config)
  for k, v = config() do
    print(k .. ": " .. v)
  end
end
```

The Go:

```go
func main() {
        // .. set up state, load script, etc...
        config := map[string]interface{}{
                "from": "name",
                "to":   "other_name",
        }
        err := L.CallByParam(lua.P{
                Fn:      L.GetGlobal("doWork"),
                NRet:    0,
                Protect: true,
        }, luar.New(L, config))
        if err != nil {
                panic(err) // Panic happens here
        }
}
```

Not sure what I'm doing wrong, this is per the documentation. I've also tried a `map[string]string` but ultimately this data is fed in from a JSON parse so it's a `map[string]interface{}`

As a side note, if I call `config()` outside of the loop header everything works fine. It just returns a function. I'm not quite sure what's breaking here, it's only when trying to do this loop.

**Comment by bontibon** [comment]
I am not able to replicate the issue you are having. I did, however, have to modify your code from:

```lua
for k, v = config() do
```

To
```lua
for k, v in config() do
```

Please ensure the script is loading correctly and without errors.

**Comment by bbuck** [comment]
Interesting, that's kind of frustrating.

If that's the case (the code change) your examples in the documentation may also need to be modified:

```lua
for k, v = places() do
  print(k .. ": " .. v)
end
```

**Comment by bontibon** [comment]
Thank you for noticing that. I have updated in the example (5b126633205f2ae1f20319504925000dc9d49d8e).

**Comment by bbuck** [comment]
No worries, thanks for the awesome project.

**Comment by bbuck** [comment]
It actually appears that I had mistaken the origin of this issue. This occurs when you use a type aliased as something else, perhaps this was never meant to be supported, but I feel like it should be if it's possible.

I had a type in Go:

```go
type Record map[string]interface{}

func (r Record) Get(name string) interface{} {
        m := map[string]interface{}(r)
        return m[key]
}

func (r Record) Set(name string, value interface{}) error {
        m := map[string]interface{}(r)
        m[key] = val

        return nil
}
```

Passing this into the script was causing the problem:

```lua
function transform(config, source, target)
  local name = source:get("name")
  -- .. other stuff
end
```

This was causing the problem.

**Comment by bontibon** [comment]
That functionality is not supported. The reason is that the Go map syntax cannot be translated to Lua.  In Lua, `obj.key` and `obj["key"]` are the same, but in Go, they are not. Supporting methods on custom map types would result in ambiguity to what is being referenced.

**Comment by bbuck** [comment]
That makes sense, now that I'm aware of that I won't be running into these issues again.
