### ISSUE TITLE
I can't call functions of structs that are created via NewType()

### ISSUE THREAD

**Issue by Zireael07** [layeh/gopher-luar#30]
Go:

```go
type GameEntity struct {
	ID     int
	Components map[string]Component
}

func (e *GameEntity) setupComponentsMap() {
	e.Components = make(map[string]Component)
}


L.SetGlobal("Ent", luar.NewType(L, GameEntity{}))
```

Lua:
```lua
--test Go interop 
ent = Ent()
print(ent)
--(calling functions)
ent:setupComponentsMap()
```

error: attempt to call a non-function object

If I create ent on Go side and follow e.g. the example in the readme, functions are called no problem. This kind of beats the whole purpose of using luar in the first place to avoid manually writing glue code...

**Comment by bontibon** [comment]
Try the following instead (note that you are creating a pointer to a `GameEntity`):

```go
L.SetGlobal("Ent", luar.NewType(L, &GameEntity{}))
```

**Comment by bontibon** [comment]
You also may have to make `(*GameEntity).setupComponentsMap` exported:

```go
func (e *GameEntity) SetupComponentsMap() {
	e.Components = make(map[string]Component)
}
```

**Comment by Zireael07** [comment]
The example in the README.md doesn't require any "making exported" of the functions of the User(), though - it just works.

**Comment by bontibon** [comment]
`SetToken` method and `Name` fields are already exported in the example; that's why it just works. Accessing non-exported fields and calling non-exported methods is not supported.

**Comment by Zireael07** [comment]
How are they exported? This is super confusing and docs aren't helpful.

For reference, this code works:

`
type GameEntity struct {
	ID     int
	Components map[string]Component
}

func (e *GameEntity) AddComponentLua(componentName string) {
	log.Printf("Lua tried adding component %s", componentName)
}

//test Lua->Go interop
	ent := &GameEntity{}
    L.SetGlobal("ent", luar.New(L, ent)) `

Lua:
`print(ent)
--(calling functions)
--ent:setupComponentsMap()
ent:AddComponentLua("TestComp")`

**Comment by bontibon** [comment]
Go defines what is exported: https://golang.org/ref/spec#Exported_identifiers

Here is a working example using NewType:

```go
package main

import (
	"log"

	"github.com/yuin/gopher-lua"
	"layeh.com/gopher-luar"
)

type Component struct{}

type GameEntity struct {
	ID         int
	Components map[string]Component
}

func (e *GameEntity) AddComponentLua(componentName string) {
	log.Printf("Lua tried adding component %s", componentName)
}

func main() {
	L := lua.NewState()
	defer L.Close()

	L.SetGlobal("Ent", luar.NewType(L, GameEntity{}))
	if err := L.DoString(`ent = Ent(); print(ent); ent:AddComponentLua("TestComp")`); err != nil {
		panic(err)
	}
}
```

**Comment by Zireael07** [comment]
Aaah, that clears this particular issue up, thank you!

**Comment by GwynethLlewelyn** [comment]
**Definitely** something to add to the README (which is very sparse anyway), or, at least, get it to be fully documented through https://pkg.go.dev/github.com/layeh/gopher-luar — if I didn't remember to look at the _closed_ issues, I would never figured it out from the provided documentation... 😭
