### ISSUE TITLE
argument of method cannot be set for go function because the type error is not thrown 

### ISSUE THREAD

**Issue by ccbhj** [layeh/gopher-luar#36]
issue: using an table carrying string value to set a struct that is expecting a integer will cause panic instead of throwing type error 
go Version: go.17
luar version: 	layeh.com/gopher-luar v1.0.10
gopher-lua: 	github.com/yuin/gopher-lua v0.0.0-20190206043414-8bfc7677f583

example:
```
type B struct {
	I int
}

type A struct {
	B *B
}

func test(a *A) {
	if a != nil && a.B != nil {
		print(a.B.I)
	}
}

func main() {
	L := lua.NewState()
	defer L.Close()

	L.SetGlobal("test", luar.New(L, test))

	code := `
		local a = { B = {I = "10"} }
		test(a)
	`
	if err := L.DoString(code); err != nil {
		panic(err)
	}
}
```
result in 
```
panic: reflect: call of reflect.Value.Set on zero Value
stack traceback:
        [G]: in function 'test'
        <string>:3: in main chunk
        [G]: ?

goroutine 1 [running]:
main.main()
```
caused by this line: 
https://github.com/layeh/gopher-luar/blob/6b0665c71bb633083e19fff076ce70c384b71a9c/luar.go#LL444C33-L444C33

**Comment by u873838** [comment]
Fixed in 2aa5885def8a7168875e5d2e469e4116584707c0.
