### ISSUE TITLE
Any way to "hide" methods?

### ISSUE THREAD

**Issue by cathalgarvey** [layeh/gopher-luar#6]
Hey Layeh, thanks for Luar, it's amazing. :)

I've just encountered a security problem, though, which I was hoping you could help with. I'm using luar with my new project, [listless](/cathalgarvey/listless), which implements a discussion-mailing-list scripted in Lua.

At present, there are three separate lua contexts;

* A script-as-configuration-file, from which a config struct is created and the engine destroyed
* An event-loop which creates a fresh Lua thread for each incoming mail and executes a script
* An execute-once mode used for configuring lists at setup time and for maintenance.

All of these modes are fairly owner-controlled, and it's always in the power of the owner to open security holes unwittingly through bad code. So, I'm leaving `io` and `os` and `debug` alone, and the latter two scripts even get full database access.

I'd also like to implement a 4th mode, where moderators can email the list to issue commands in a more restricted lua environment; no `io`, no `os`, no `debug`, and more closely limited options, because email is a poorly authenticated platform and abuse would be too easy otherwise.

*Coming to the problem:*

I just realised that several of the objects I'm exposing to the Lua engines are embedded-struct wrappers around rich structs that have Go `io` access, and that potentially the parent methods are exposed. So, I tried shadowing one of these dangerous methods, `email.Email.AttachFile(filename) (*email.Attachment, error)`, then went to Lua and accessed `message.AttachFile` and `message.Email.AttachFile`; different memory addresses.

So, it seems Luar is doing (as it should) a great job of iterating over methods including parent struct methods. This behaviour would normally be great, but in this case it's a problem!

Is there any way in luar to either:

1. Prevent accessing embedded structs directly, or
2. Prevent luar from enumerating embedded structs at reflection-time?

Thanks, sorry for the long post but I figure extra context helps frame the question!

**Comment by cathalgarvey** [comment]
Would I be correct in reading that the issue lies in these two functions: [addMethods](https://github.com/layeh/gopher-luar/blob/master/cache.go#L44) and [addFields](https://github.com/layeh/gopher-luar/blob/master/cache.go#L57)?

From my reading of `reflect`, which I have never yet used, it looks like it is possible to detect fields of Embedded structs: I'm not sure whether this can be used on methods of embedded structs also (are they "Fields" also, as my intuition would suggest, or not?).

If so, then by way of solution, I could try and implement a fix and issue a PR, which would probably consist of:

1. Modifying `addFields` and `addMethods` to add a 'includeAnonFields' parameter
2. Exposing at API level by one of:
    - A new function like `luar.New`, or
    - A variadic additional parameter to `luar.New`, so the API won't break, for `ReflectOptions`, which would initially include only one parameter for this use-case, but which would open up possibilities for fine-tuning later if others find they have special cases.

My preference would be the latter option; keep the API but broaden its scope.

Thoughts?

**Comment by bontibon** [comment]
Have a look at the "mt" branch I just pushed. I'm still trying to figure out the best API, but this should be a starting point. Example usage:

```go
package main

import (
	"github.com/layeh/gopher-luar"
	"github.com/yuin/gopher-lua"
)

type A struct {
}

func (*A) Public() {
	println("You can call me")
}

func (*A) Private() {
	println("Should not be able to call me")
}

type B struct {
	*A
}

func main() {
	L := lua.NewState()

	b := &B{
		A: &A{},
	}

	str := `

	b:public()
	b.A:public()
	pcall(function()
		b:private()
	end)
	pcall(function()
		b.A:private()
	end)
	pcall(function()
		b:Private()
	end)
	pcall(function()
		b.A:Private()
	end)
	pcall(function()
		local a = -b.A
		a:Private()
	end)
	`
	mt := luar.MT(L, B{})
	mt.Remove("private")
	mt.Remove("Private")

	mt = luar.MT(L, A{})
	mt.Remove("private")
	mt.Remove("Private")

	L.SetGlobal("b", luar.New(L, b))

	if err := L.DoString(str); err != nil {
		panic(err)
	}
}
```

**Comment by cathalgarvey** [comment]
Ok cool! Thanks, this will really help in my use-cases.

From here, how hard would it be to iterate and remove all but a list of methods from the Go side of things? Is that something you can do from within Lua, or would it require reflect calls to enumerate methods?

Thanks so much!

**Comment by bontibon** [comment]
This should now be easy with `Metatable.Whitelist`.

**Comment by cathalgarvey** [comment]
I love you Tim Cooper. :)

Thanks so much!

On 18 January 2016 19:16:20 GMT+00:00, Tim Cooper <notifications@github.com> wrote:
>This should now be easy with `Metatable.Whitelist`.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/layeh/gopher-luar/issues/6#issuecomment-172626677

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
