### ISSUE TITLE
New types with defaults?

### ISSUE THREAD

**Issue by dnaeon** [layeh/gopher-luar#8]
Considering the `luar.NewType` example from https://github.com/layeh/gopher-luar/blob/master/example_test.go#L1037, is there a way to set default values for the `Song` struct, so that you don't have to initialize each struct field later on?

Thanks,
Marin

**Comment by bontibon** [comment]
Instead of using `NewType`, use `New` with an initialize function. Example:

```go
newSong := func() *Song {
   return &Song{
      Title:  "Default title",
      Artist: "Default artist",
   }
}

L.SetGlobal("NewSong", luar.New(L, newSong))
```

**Comment by dnaeon** [comment]
Thanks!
